# $FreeBSD$

PORTNAME=	flat-remix
PORTVERSION=	20190109
CATEGORIES=	x11-themes
PKGNAMESUFFIX=	-icon-theme

MAINTAINER=	tagattie@yandex.com
COMMENT=	Flat Remix icon theme

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake gnome

USE_GITHUB=	yes
GH_ACCOUNT=	daniruiz

NO_ARCH=	yes
NO_BUILD=	yes

INSTALLS_ICONS=	yes

.include <bsd.port.mk>
