# $FreeBSD$

PORTNAME=	python-mpv
PORTVERSION=	0.3.9
CATEGORIES=	multimedia python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tagattie@yandex.com
COMMENT=	Python interface to the awesome mpv media player

LICENSE=	AGPLv3+

LIB_DEPENDS=	libmpv.so:multimedia/mpv

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
